aklivity/zilla

- runtime/binding-sse-kafka/src/main/java/io/aklivity/zilla/runtime/binding/sse/kafka/internal/config/SseKafkaWithConfig.java
- runtime/binding-sse-kafka/src/main/java/io/aklivity/zilla/runtime/binding/sse/kafka/internal/config/SseKafkaWithConfigAdapter.java
- runtime/binding-sse-kafka/src/main/java/io/aklivity/zilla/runtime/binding/sse/kafka/internal/config/SseKafkaWithResolver.java
- runtime/binding-sse-kafka/src/main/java/io/aklivity/zilla/runtime/binding/sse/kafka/internal/config/SseKafkaWithResult.java
- runtime/binding-sse-kafka/src/main/java/io/aklivity/zilla/runtime/binding/sse/kafka/internal/stream/SseKafkaIdHelper.java
- runtime/binding-sse-kafka/src/main/java/io/aklivity/zilla/runtime/binding/sse/kafka/internal/stream/SseKafkaProxyFactory.java
- runtime/binding-sse-kafka/src/test/java/io/aklivity/zilla/runtime/binding/sse/kafka/internal/config/SseKafkaWithConfigAdapterTest.java
- runtime/binding-sse-kafka/src/test/java/io/aklivity/zilla/runtime/binding/sse/kafka/internal/stream/SseKafkaIdHelperTest.java
- runtime/binding-sse-kafka/src/test/java/io/aklivity/zilla/runtime/binding/sse/kafka/internal/stream/SseKafkaProxyIT.java
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/config/proxy.with.topic.and.event.id.json
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/schema/sse.kafka.schema.patch.json
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/kafka/handshake.reconnect.with.etag/client.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/kafka/handshake.reconnect.with.etag/server.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/kafka/server.sent.messages.with.etag/client.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/kafka/server.sent.messages.with.etag/server.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/kafka/server.sent.messages.with.null.key/client.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/kafka/server.sent.messages.with.null.key/server.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/sse/handshake.reconnect.with.etag/client.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/sse/handshake.reconnect.with.etag/server.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/sse/handshake.reconnect.with.key.and.etag/client.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/sse/handshake.reconnect.with.key.and.etag/server.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/sse/server.sent.messages.with.etag/client.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/sse/server.sent.messages.with.etag/server.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/sse/server.sent.messages.with.key.and.etag/client.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/sse/server.sent.messages.with.key.and.etag/server.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/sse/server.sent.messages.with.null.key/client.rpt
- specs/binding-sse-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/sse/kafka/streams/sse/server.sent.messages.with.null.key/server.rpt
- specs/binding-sse-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/sse/kafka/config/SchemaTest.java
- specs/binding-sse-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/sse/kafka/streams/KafkaIT.java
- specs/binding-sse-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/sse/kafka/streams/SseIT.java
Support configuration of SSE event id to include message key, fix #27.
Support including etag from kafka message with progress, fix #26.
> Support key and etag in event id

- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/internal/config/HttpKafkaWithProduceResult.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/internal/stream/HttpKafkaProxyFactory.java
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/post.items.prefer.async.delayed/client.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/post.items.prefer.async.delayed/server.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/post.items.prefer.async.ignored/client.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/post.items.prefer.async.ignored/server.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/post.items.prefer.async/client.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/post.items.prefer.async/server.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/post.items/client.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/post.items/server.rpt
> Use content-length instead of transfer-encoding chunked for correlated responses

- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/internal/config/HttpKafkaWithProduceResult.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/internal/config/HttpKafkaWithResolver.java
- runtime/binding-http-kafka/src/test/java/io/aklivity/zilla/runtime/binding/http/kafka/internal/stream/HttpKafkaProxyIT.java
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/delete.item.if.match.no.etag/client.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/delete.item.if.match.no.etag/server.rpt
- specs/binding-http-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/http/kafka/streams/HttpIT.java
> Skip adding if-match header to kafka message if etag not present

- runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/config/HttpAuthorizationConfig.java
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/application/rfc7230/authorization/authorize.credentials.query/client.rpt
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/application/rfc7230/authorization/authorize.credentials.query/server.rpt
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/application/rfc7540/authorization/authorize.credentials.query/client.rpt
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/application/rfc7540/authorization/authorize.credentials.query/server.rpt
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/network/rfc7230/authorization/authorize.credentials.query/client.rpt
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/network/rfc7230/authorization/authorize.credentials.query/server.rpt
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/network/rfc7540/authorization/authorize.credentials.query/client.rpt
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/network/rfc7540/authorization/authorize.credentials.query/server.rpt
> Use & as end of token separator for query parameter values

- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/ConfigureTask.java
`https` is repeated twice in the if condition. This means that if the protocol in the URL to the Zilla JSON config file is `http`, then the `java.net.http.HttpClient` client is not used to retrieve the JSON configuration. Instead, a `URLConnection` is used.
@jfallows I think this will still work with a `configURL.openConnection()`. If this was the intended behavior, then i think the other approach will be to simply the if condition
Signed-off-by: Alfusainey Jallow <alf.jallow@gmail.com>
> BugFix: process configURL if the protocol is http

- README.md
It worked well with Java 17 and Java 19:
```
Benchmark                  Mode  Cnt         Score         Error  Units
BufferBM.batched          thrpt   15  11663496.292 ±   32940.441  ops/s
BufferBM.multiple         thrpt   15  14837814.742 ± 2768697.168  ops/s
BufferBM.multiple:reader  thrpt   15   2884675.668 ± 2160878.065  ops/s
BufferBM.multiple:writer  thrpt   15  11953139.074 ± 2638964.717  ops/s
BufferBM.single           thrpt   15  11719456.989 ±   68473.560  ops/s
```
Side note: the numbers are surprisingly worse with an M1 and a newer version of Java. 
``` …
```
> Document how to run the benchmark with Java 16+

- README.md
> Update zilla readme to address yaml changes

- incubator/binding-kafka-grpc/src/main/java/io/aklivity/zilla/runtime/binding/kafka/grpc/internal/KafkaGrpcBinding.java
- incubator/binding-kafka-grpc/src/main/java/io/aklivity/zilla/runtime/binding/kafka/grpc/internal/KafkaGrpcBindingContext.java
- incubator/binding-kafka-grpc/src/main/java/io/aklivity/zilla/runtime/binding/kafka/grpc/internal/stream/KafkaGrpcRemoteServerFactory.java
Kafka Grpc does signal based on the number of cores and causes to process the same message multiple times
> Fix number of signals in Kafka Grpc

- incubator/binding-grpc-kafka.spec/pom.xml
- incubator/binding-grpc-kafka.spec/src/main/java/io/aklivity/zilla/specs/binding/grpc/kafka/internal/GrpcKafkaFunctions.java
- incubator/binding-grpc-kafka.spec/src/main/resources/META-INF/zilla/grpc_kafka.idl
- incubator/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/streams/grpc/fetch/reliable.unary.rpc/client.rpt
- incubator/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/streams/grpc/fetch/reliable.unary.rpc/server.rpt
- incubator/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/streams/grpc/fetch/unreliable.unary.rpc/client.rpt
- incubator/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/streams/grpc/fetch/unreliable.unary.rpc/server.rpt
- incubator/binding-grpc-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/grpc/kafka/internal/GrpcKafkaFunctionsTest.java
- incubator/binding-grpc-kafka/pom.xml
- incubator/binding-grpc-kafka/src/main/java/io/aklivity/zilla/runtime/binding/grpc/kafka/internal/config/GrpcKafkaWithFetchResult.java
- incubator/binding-grpc-kafka/src/main/java/io/aklivity/zilla/runtime/binding/grpc/kafka/internal/config/GrpcKafkaWithResolver.java
- incubator/binding-grpc-kafka/src/main/java/io/aklivity/zilla/runtime/binding/grpc/kafka/internal/stream/GrpcKafkaIdHelper.java
- incubator/binding-grpc-kafka/src/main/java/io/aklivity/zilla/runtime/binding/grpc/kafka/internal/stream/GrpcKafkaProxyFactory.java
We were sending kafka progress bytes as it is without encoding them to last message id.
> Encode kafka progress as last message id

- incubator/exporter-prometheus.spec/src/main/scripts/io/aklivity/zilla/specs/exporter/prometheus/schema/prometheus.schema.patch.json
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/DispatchAgent.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/stream/Target.java
Chaining MessageConsumers and MetricHandlers allows optimal composition of metrics and stream handlers, with zero overhead when no metrics are collected, and minimal overhead when metrics are collected.
Fix #213
> Minimize performance overhead for metric collection

- incubator/exporter-prometheus/src/main/java/io/aklivity/zilla/runtime/exporter/prometheus/internal/descriptor/PrometheusMetricDescriptor.java
- incubator/metrics-http.spec/src/main/scripts/io/aklivity/zilla/specs/metrics/http/schema/http.schema.patch.json
- incubator/metrics-http/pom.xml
- incubator/metrics-http/src/main/java/io/aklivity/zilla/runtime/metrics/http/internal/HttpActiveRequestsMetric.java
- incubator/metrics-http/src/main/java/io/aklivity/zilla/runtime/metrics/http/internal/HttpActiveRequestsMetricContext.java
- incubator/metrics-http/src/main/java/io/aklivity/zilla/runtime/metrics/http/internal/HttpDurationMetric.java
- incubator/metrics-http/src/main/java/io/aklivity/zilla/runtime/metrics/http/internal/HttpDurationMetricContext.java
- incubator/metrics-http/src/main/java/io/aklivity/zilla/runtime/metrics/http/internal/HttpMetricGroup.java
- incubator/metrics-http/src/main/java/io/aklivity/zilla/runtime/metrics/http/internal/HttpUtils.java
- incubator/metrics-http/src/test/java/io/aklivity/zilla/runtime/metrics/http/internal/HttpMetricGroupTest.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/DispatchAgent.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/metrics/Metric.java
This change adds these metrics:
- `http.active.requests` to track the number of currently active http requests (gauge) 
- `http.duration` to track to track the duration of http requests (histogram)
Fixes #111
> Add http.active.requests and http.duration metrics

- runtime/binding-kafka/src/test/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/CacheFetchIT.java
- specs/binding-kafka.spec/src/main/java/io/aklivity/zilla/specs/binding/kafka/internal/KafkaFunctions.java
- specs/binding-kafka.spec/src/main/resources/META-INF/zilla/kafka.idl
- specs/binding-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/kafka/internal/KafkaFunctionsTest.java
> Consumer group kafka function support

- cloud/helm-chart/src/main/helm/README.md
Fix the requirements versions in the helm chart's readme:
- Kubernetes: `>=1.23.x`
- Helm: `>=3.8.x`
> Fix the requirements versions in helm chart readme

- runtime/command-start/src/main/java/io/aklivity/zilla/runtime/command/start/internal/airline/ZillaStartCommand.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/ConfigurationManager.java
Simplify `zilla start` output when `zilla.json` not found.
> Eliminate zilla.json warning if file not present

- runtime/binding-kafka/src/test/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/CacheFetchIT.java
Set the flaky test `CacheFetchIT.shouldFetchFilterSyncWithData` to `@Ignore` for now to unblock builds.
Created an issue to fix it: #350
> Ignore CacheFetchIT.shouldFetchFilterSyncWithData

- .github/workflows/build.yml
Use JDK 20 in the GitHub Actions build.
> Include JDK 20 in build matrix

- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/BindingConfigBuilder.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/config/BindingConfigsAdapter.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/internal/config/BindingConfigsAdapterTest.java
Provide shorthand syntax for `BindingConfigBuilder.exit(...)` while ensuring that `route` `order` is preserved automatically.
> Support binding config builder exit

- runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/stream/HttpServerFactory.java
When request window maximum is too low, such as `0` for `sse` request window which expects only `GET` request with no body, then calculated available `length` could become negative, adversely affecting how we track progress through the request body.
Fixes #293
> Request data length is non-negative

- cloud/docker-image/pom.xml
When building locally, license check was failing on locally generated `.zilla` engine directory.
> Support build after local docker zpm install

- cloud/docker-image/pom.xml
- incubator/catalog-schema-registry/src/main/moditect/module-info.java
- incubator/command-log/pom.xml
- manager/pom.xml
- pom.xml
- runtime/binding-kafka/pom.xml
- runtime/binding-kafka/src/main/moditect/module-info.java
Fix issue with kafka binding module dependencies for zpm install using shaded JAR.
> Schema registry docker build shaded

- runtime/binding-tcp/src/main/java/io/aklivity/zilla/runtime/binding/tcp/internal/stream/TcpClientFactory.java
- runtime/binding-tcp/src/main/java/io/aklivity/zilla/runtime/binding/tcp/internal/stream/TcpState.java
If socket channel is still connecting asynchronously while `WINDOW` frame arrives proactively on reply stream before `BEGIN` is sent, then attempting to read from the socket channel causes a `NotYetConnectedException`.
If we guard against that, then the socket read will happen when the `OP_READ` handler is set after the socket channel connects successfully.
> Ensure socket channel has finished connecting before attempting to read

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientGroupFactory.java
- runtime/binding-kafka/src/main/zilla/protocol.idl
- runtime/binding-kafka/src/test/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/ClientGroupIT.java
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/network/offset.fetch.v0/topic.offset.info/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/network/offset.fetch.v0/topic.offset.info/server.rpt
Currently, we are closing the group application stream once we are done finding coordinator or describe configs. It is passing now because the scripts are not complete. We are going to change the scripts in connections pool PR.
> Don't close group stream on cluster and describe streams closer

- runtime/binding-http/pom.xml
- runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/HttpBinding.java
- runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/HttpConfiguration.java
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/schema/http.with.validators.schema.patch.json
Add http request validators feature flag to be enabled when http runtime enforcement is completed. Configuration syntax looks good, but disabled by default for now.
> Http request validators feature flag

- cloud/helm-chart/src/main/helm/templates/deployment.yaml
- cloud/helm-chart/src/main/helm/values.yaml
The default `values.yaml` doesn't need to override the desired image version and can be removed. This will enable a 1-1 relationship between the `chartVersion` and the `appVersion` that is already being set in the pom:
```
<configuration>
<chartDirectory>src/main/helm</chartDirectory>
<chartVersion>${project.version}</chartVersion>
<appVersion>${project.version}</appVersion>
...
```
The repository is the only unique value we need to default based on the `deployment.yaml`. Users will be able to overwrite these values in their own `values.yaml`:
```
image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
```
Fixes #487
> update helm configs so appVersion is used as the tag

- cloud/helm-chart/src/main/helm/templates/deployment.yaml
- cloud/helm-chart/src/main/helm/values.yaml
Add `extraEnv` option to offer an easier way of overriding environment variables.
Fixes #520
> Add extraEnv to Deployment in the helm chart

- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/DispatchAgent.java
Create an appropriate buffer with the size that accommodates data frame payload
Fixes #527
> Create an appropriate buffer with the size that accommodates signal frame payload

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/KafkaConfiguration.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientProduceFactory.java
- runtime/binding-kafka/src/test/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/ClientMergedIT.java
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/produce/message.value.100k/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/produce/message.value.100k/server.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/produce/message.value.10k/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/produce/message.value.10k/server.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/produce/message.values.sequential/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/produce/message.values.sequential/server.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/network/produce.v3/message.values.sequential/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/network/produce.v3/message.values.sequential/server.rpt
Adjust padding for larger message header and don't include partial data while computing crc32c value
Fixes #368
> Adjust padding for larger message header and don't include partial data while computing crc32c 

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientGroupFactory.java
Unexpected flush causes NPE in the connection pool 
Fixes #546
> Use coordinator member list to check if the heartbeat is allowed

- runtime/binding-http-filesystem/src/main/java/io/aklivity/zilla/runtime/binding/http/filesystem/internal/stream/HttpFileSystemProxyFactory.java
- specs/binding-http-filesystem.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/filesystem/streams/http/client.read.file.map.modified/client.rpt
- specs/binding-http-filesystem.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/filesystem/streams/http/client.read.file.map.modified/server.rpt
- specs/binding-http-filesystem.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/filesystem/streams/http/client.read.file.map.not.modified/client.rpt
- specs/binding-http-filesystem.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/filesystem/streams/http/client.read.file.map.not.modified/server.rpt
- specs/binding-http-filesystem.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/filesystem/streams/http/client.read.file.with.query/client.rpt
- specs/binding-http-filesystem.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/filesystem/streams/http/client.read.file.with.query/server.rpt
- specs/binding-http-filesystem.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/filesystem/streams/http/client.read.file/client.rpt
- specs/binding-http-filesystem.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/filesystem/streams/http/client.read.file/server.rpt
[Header field names MUST be converted to lowercase prior to their encoding in HTTP/2.](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2)  Etag header name has upper case as first later
Fixes #551
> Etag header field name MUST be converted to lowercase prior to their encoding in HTTP/2

- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/internal/stream/HttpKafkaProxyFactory.java
- runtime/binding-http-kafka/src/test/java/io/aklivity/zilla/runtime/binding/http/kafka/internal/stream/HttpKafkaProxyIT.java
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/get.items.fragmented/client.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/get.items.fragmented/server.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/kafka/get.items.fragmented/client.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/kafka/get.items.fragmented/server.rpt
- specs/binding-http-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/http/kafka/streams/HttpIT.java
- specs/binding-http-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/http/kafka/streams/KafkaIT.java
Due to missing fragmentation support, we kept adding additional separators(`,`)  
Fixes #528
> Handle fragmentation in HttpFetchManyProxy

- incubator/command-generate/src/main/java/io/aklivity/zilla/runtime/command/generate/internal/airline/ConfigGenerator.java
- incubator/command-generate/src/main/java/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/http/proxy/AsyncApiHttpProxyConfigGenerator.java
- incubator/command-generate/src/main/java/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/model/Channel.java
- incubator/command-generate/src/main/java/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/model/Parameter.java
- incubator/command-generate/src/main/java/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/model/Schema.java
- incubator/command-generate/src/main/java/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/mqtt/proxy/AsyncApiMqttProxyConfigGenerator.java
- incubator/command-generate/src/main/java/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/view/ChannelView.java
- incubator/command-generate/src/main/java/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/view/MessageView.java
- incubator/command-generate/src/main/java/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/view/Resolvable.java
- incubator/command-generate/src/test/java/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/http/proxy/AsyncApiHttpProxyConfigGeneratorTest.java
- incubator/command-generate/src/test/resources/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/http/proxy/complete/zilla.yaml
- incubator/command-generate/src/test/resources/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/http/proxy/jwt/asyncapi.yaml
- incubator/command-generate/src/test/resources/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/http/proxy/plain/asyncapi.yaml
- incubator/command-generate/src/test/resources/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/http/proxy/tls/asyncapi.yaml
- incubator/command-generate/src/test/resources/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/http/proxy/validator/asyncapi.yaml
- incubator/command-generate/src/test/resources/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/http/proxy/validator/zilla.yaml
- incubator/command-generate/src/test/resources/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/mqtt/proxy/complete/zilla.yaml
- incubator/command-generate/src/test/resources/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/mqtt/proxy/validator/zilla.yaml
Include validation in the generate command in the `asyncapi.http.proxy` template
Fixes #460
> Include validation in the `asyncapi.http.proxy` generator

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaMergedFactory.java
The initial value of `mergedReplyBudgetId` was incorrect that caused zilla to crash under certain conditions. This change fixes this bug.
Fixes #578
> Fix mergedReplyBudgetId

- specs/exporter-prometheus.spec/src/main/scripts/io/aklivity/zilla/specs/exporter/prometheus/schema/prometheus.schema.patch.json
The prometheus exporter schema has a typo that is fixed by this PR.
Fixes #569
> Fix prometheus exporter schema

- incubator/command-log/src/main/java/io/aklivity/zilla/runtime/command/log/internal/LogCommand.java
- incubator/command-log/src/main/java/io/aklivity/zilla/runtime/command/log/internal/LogStreamsCommand.java
- incubator/command-log/src/main/java/io/aklivity/zilla/runtime/command/log/internal/LoggableStream.java
Create a command line switch `-p` or `--payload` to include the payload of the `DATA` frames as a hex string in the output of the `log` command.
> Include data payload as hex in the output of log command

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaMergedFactory.java
- specs/binding-kafka.spec/src/main/java/io/aklivity/zilla/specs/binding/kafka/internal/KafkaFunctions.java
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/merged/merged.fetch.message.ack/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/merged/merged.fetch.message.ack/server.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/merged/unmerged.group.fetch.message.ack/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/merged/unmerged.group.fetch.message.ack/server.rpt
We should include metadata as part of merge reply begin ex
```
read zilla:begin.ext ${kafka:matchBeginEx()
.typeId(zilla:id("kafka"))
.merged()
.capabilities("FETCH_ONLY")
.topic("test")
.partition(0, 2, 2, 2, "test-meta")
.build()
.build()}
```
Fixes #601
> Include metadata and partitionOffset into merge reply begin

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientProduceFactory.java
While testing Zilla with `zilla.binding.kafka.debug=true`, I was encountering `java.util.MissingFormatArgumentException` errors that would cause Zilla to exit. This change mimics what I saw elsewhere in the Kafka binding where bytes were being logged.
> Fix `java.util.MissingFormatArgumentException` when using Kafka debugging.

- incubator/exporter-otlp.spec/src/main/scripts/io/aklivity/zilla/specs/exporter/otlp/schema/otlp.schema.patch.json
- specs/binding-grpc.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/schema/grpc.schema.patch.json
- specs/binding-kafka-grpc.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/grpc/schema/kafka.grpc.schema.patch.json
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/schema/kafka.schema.patch.json
- specs/binding-mqtt-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/mqtt/kafka/schema/mqtt.kafka.schema.patch.json
This fixes some errors, incorrect fields, and inconsistencies in the zilla schema.
https://github.com/aklivity/zilla/issues/637
> Json schema errors

- runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/stream/HttpClientFactory.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientFetchFactory.java
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/application/rfc7540/flow.control/server.sent.100k.message/client.rpt
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/application/rfc7540/flow.control/server.sent.100k.message/server.rpt
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/network/rfc7540/flow.control/server.sent.100k.message/client.rpt
This is a current understanding of the issue
```
zilla: offset <= stable <= latest
which means offset <= stable, stable <= latest, offset <= latest
kafka: offset < stable <= high water mark
which means offset < stable, stable <= high water mark, offset < high water mark
```
Due to this invariant sometimes we may get into a state where the fix to send a flush when stableOffset or latestOffset has advanced (with no records) after records have been sent or caught up to the latest offset so at least one FLUSH was already sent.
Fixes #666
> Update latest and stable offset if it was in stabilizing state

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaCacheGroupFactory.java
- runtime/binding-kafka/src/test/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/CacheGroupIT.java
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/group/server.sent.read.abort.after.join.group/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/group/server.sent.read.abort.after.join.group/server.rpt
- specs/binding-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/kafka/streams/application/GroupIT.java
Due to the wrong state in the group cache we are not propagating the reset.
Fixes #620
> Remove wrong state assignment in the group cache

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaCacheClientProduceFactory.java
Reject stream if deferred is not set for the fragmented message
> Reject stream if deferred is not set for the fragmented message

- cloud/docker-image/pom.xml
The head of develop doesn't build with this error because the path in the exclusion config is to an old file location.
```
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:4.2:check (default) on project docker-image: Unable to find a comment style definition for some files. You may want to add a custom mapping for the relevant file extensions. -> [Help 1]
```
> update license exclude path to include both zpmw files

- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigAnnotator.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/EngineConfigReader.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/config/EngineConfigAnnotatorTest.java
- specs/exporter-prometheus.spec/src/main/scripts/io/aklivity/zilla/specs/exporter/prometheus/schema/prometheus.schema.patch.json
Zilla is validating env vars before replacing them
Fixes #795
> Zilla is validating env vars before replacing them

- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/schema/kafka.schema.patch.json
Fix kafka sasl schema validation to support expressions
Fixes #795
> Fix kafka sasl schema validation to support expressions

- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/behavior/ZillaChannelAddress.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/behavior/ZillaChannelAddressFactory.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/types/ZillaTypeSystem.java
> Support k3po ephemeral option

- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/Engine.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/BindingConfig.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineManager.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/namespace/NamespacedId.java
This is helpful for composite binding adapters referencing vaults that may themselves be cross-namespace.
> Include qualified vault name on binding

- incubator/model-avro.spec/src/main/scripts/io/aklivity/zilla/specs/model/avro/schema/avro.schema.patch.json
- incubator/model-json.spec/src/main/scripts/io/aklivity/zilla/specs/model/json/schema/json.schema.patch.json
- incubator/model-protobuf.spec/src/main/scripts/io/aklivity/zilla/specs/model/protobuf/schema/protobuf.schema.patch.json
Issue: We can configure structure Model without specifying Catalog. But for any structure Model validation catalog is required.
Fix: Schema change for Structured Model [`avro, json, protobuf`] to require Catalog config.
> Structured models require `catalog` config

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientConnectionPool.java
Race condition causes streamsByInitialId to be cleaned up early then request gets acked causing NPE.
Fixes #762
> Fix NPE in connection pool due to race condition

- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineManager.java
This change fixes a bug where the binding metadata is not saved to the `bindings` file in the case of composite bindings which causes missing information in the `dump` command.
> Fix binding metadata for composite bindings

- incubator/binding-openapi-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/openapi/asyncapi/internal/config/OpenapiAsyncCompositeBindingAdapter.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/config/HttpKafkaWithFetchConfig.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/config/HttpKafkaWithFetchConfigBuilder.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/config/HttpKafkaWithFetchFilterConfig.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/config/HttpKafkaWithFetchFilterConfigBuilder.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/config/HttpKafkaWithFetchFilterHeaderConfig.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/config/HttpKafkaWithFetchFilterHeaderConfigBuilder.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/internal/config/HttpKafkaWithFetchConfigAdapter.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/internal/config/HttpKafkaWithResolver.java
- runtime/binding-http-kafka/src/test/java/io/aklivity/zilla/runtime/binding/http/kafka/internal/config/HttpKafkaWithConfigAdapterTest.java
Add key filter support in openapi asyncapi mapping.
> Add key filter support in openapi asyncapi mapping

- incubator/exporter-otlp.spec/src/main/scripts/io/aklivity/zilla/specs/exporter/otlp/config/event.yaml
- incubator/exporter-otlp.spec/src/main/scripts/io/aklivity/zilla/specs/exporter/otlp/config/metrics.yaml
- incubator/exporter-otlp.spec/src/main/scripts/io/aklivity/zilla/specs/exporter/otlp/schema/otlp.schema.patch.json
- incubator/exporter-otlp/src/test/java/io/aklivity/zilla/runtime/exporter/otlp/internal/config/SchemaTest.java
This adds back the missing schema for overrides in the `exporter-otlp` module.
> Fix exporter-otlp schema

- incubator/command-generate/src/test/resources/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/http/proxy/complete/zilla.yaml
- incubator/command-generate/src/test/resources/io/aklivity/zilla/runtime/command/generate/internal/asyncapi/http/proxy/validator/zilla.yaml
- incubator/command-generate/src/test/resources/io/aklivity/zilla/runtime/command/generate/internal/openapi/http/proxy/complete/zilla.yaml
- incubator/command-generate/src/test/resources/io/aklivity/zilla/runtime/command/generate/internal/openapi/http/proxy/validator/zilla.yaml
- incubator/model-avro.spec/src/main/scripts/io/aklivity/zilla/specs/model/avro/schema/avro.schema.patch.json
- incubator/model-core.spec/src/main/scripts/io/aklivity/zilla/specs/model/core/config/int64.model.yaml
- incubator/model-core.spec/src/main/scripts/io/aklivity/zilla/specs/model/core/config/string.model.yaml
- incubator/model-core.spec/src/main/scripts/io/aklivity/zilla/specs/model/core/schema/int32.schema.patch.json
- incubator/model-core.spec/src/main/scripts/io/aklivity/zilla/specs/model/core/schema/int64.schema.patch.json
- incubator/model-core.spec/src/main/scripts/io/aklivity/zilla/specs/model/core/schema/string.schema.patch.json
- incubator/model-core.spec/src/test/java/io/aklivity/zilla/specs/model/core/config/Int64SchemaTest.java
- incubator/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/config/Int64ModelConfigBuilder.java
- incubator/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/config/StringModelConfig.java
- incubator/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/config/StringModelConfigBuilder.java
- incubator/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/internal/StringState.java
- incubator/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/internal/StringValidatorEncoding.java
- incubator/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/internal/StringValidatorHandler.java
- incubator/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/internal/config/Int32ModelConfigAdapter.java
- incubator/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/internal/config/Int64ModelConfigAdapter.java
- incubator/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/internal/config/StringModelConfigAdapter.java
- incubator/model-core/src/test/java/io/aklivity/zilla/runtime/model/core/internal/StringEncodingTest.java
- incubator/model-core/src/test/java/io/aklivity/zilla/runtime/model/core/internal/StringValidatorTest.java
- incubator/model-core/src/test/java/io/aklivity/zilla/runtime/model/core/internal/config/Int32ModelConfigAdapterTest.java
- incubator/model-core/src/test/java/io/aklivity/zilla/runtime/model/core/internal/config/Int64ModelConfigAdapterTest.java
- incubator/model-core/src/test/java/io/aklivity/zilla/runtime/model/core/internal/config/StringModelConfigAdapterTest.java
- incubator/model-json.spec/src/main/scripts/io/aklivity/zilla/specs/model/json/schema/json.schema.patch.json
- incubator/model-protobuf.spec/src/main/scripts/io/aklivity/zilla/specs/model/protobuf/schema/protobuf.schema.patch.json
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/config/KafkaTopicConfigAdapter.java
- specs/engine.spec/src/main/scripts/io/aklivity/zilla/specs/engine/schema/engine.schema.json
- specs/engine.spec/src/main/scripts/io/aklivity/zilla/specs/engine/schema/model/test.schema.patch.json
string validation
- max and min length
- regular expressions
> String Validator improvement to support OpenAPI & AsyncAPI specs

- incubator/model-json/src/main/java/io/aklivity/zilla/runtime/model/json/internal/JsonModelHandler.java
- incubator/model-json/src/main/java/io/aklivity/zilla/runtime/model/json/internal/JsonValidatorHandler.java
> zilla crash while using model-json and schema is not found

- incubator/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/model/AsyncapiAddress.java
- incubator/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/model/AsyncapiReply.java
- incubator/binding-openapi-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/openapi/asyncapi/internal/config/OpenapiAsyncCompositeBindingAdapter.java
- incubator/binding-openapi/src/main/java/io/aklivity/zilla/runtime/binding/openapi/internal/model/OpenapiSchema.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/config/HttpKafkaWithProduceConfigBuilder.java
Support HTTP prefer async with OpenAPI
Fixes #876
>  Support HTTP prefer async with OpenAPI

- runtime/binding-kafka/src/test/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/CacheMergedIT.java
refer: https://github.com/aklivity/zilla/pull/923
> IT to validate null message in binding-kafka with Model configured 

- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineWorker.java
`zilla dump` was crashing due to `java.nio.file.NoSuchFileException`, as `bindings` was not found in /var/run/zilla directory. But it should have been generated on startup for worker-0.
> zilla dump : bindings not found in /var/runtime/zilla directory

- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineWorker.java
Namespaces are attached an async way in the case of simple bindings. This creates a race condition, so the `bindings` file is created empty, breaking the `dump` command. This change fixes that bug.
> Ensure binding types are populated for `zilla dump` to dissect protocol-specific frames

- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/ExporterConfig.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/config/ExporterConfigBuilder.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/config/ExporterAdapter.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineManager.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/internal/config/TelemetryConfigsAdapterTest.java
This change add vault parameter to exporter in the engine.
> Add vault parameter to exporter

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/KafkaConfiguration.java
When `zilla.binding.kafka.client.id` property is not specified, we default to `zilla` but not when using the client id as part of the default kafka instance id.
This change allows kafka instance id to use the default kafka client id `zilla`.
> Use default kafka client id for kafka client instance id

- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/DuplexIT.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/behavior/DefaultZillaChannelConfig.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/behavior/DefaultZillaServerChannelConfig.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/behavior/ZillaChannel.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/behavior/ZillaChannelAddressFactory.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/behavior/ZillaChannelConfig.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/behavior/ZillaEngine.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/behavior/ZillaPartition.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/behavior/ZillaScope.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/behavior/ZillaStreamFactory.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/behavior/ZillaTarget.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/k3po/ext/types/ZillaTypeSystem.java
- runtime/engine/src/test/scripts/io/aklivity/zilla/runtime/engine/test/k3po/ext/duplex/timestamps.false/client.rpt
- runtime/engine/src/test/scripts/io/aklivity/zilla/runtime/engine/test/k3po/ext/duplex/timestamps.false/server.rpt
Allows timestamps to be disabled via script options in k3po zilla transport.
Needed by command-dump for ITs to produce predictable output for comparison to expected output.
> Support configuration of timestamps in zilla transport for k3po

- runtime/binding-openapi/src/main/java/io/aklivity/zilla/runtime/binding/openapi/internal/streams/OpenapiClientFactory.java
- runtime/binding-openapi/src/main/java/io/aklivity/zilla/runtime/binding/openapi/internal/streams/OpenapiServerFactory.java
Use flyweight fields instead of class fields for control.
Fixes #1004
> Use flyweight fields instead of class fields for control

- runtime/binding-mqtt/pom.xml
- runtime/binding-mqtt/src/main/java/io/aklivity/zilla/runtime/binding/mqtt/internal/MqttEventContext.java
- runtime/binding-mqtt/src/main/java/io/aklivity/zilla/runtime/binding/mqtt/internal/MqttEventFormatter.java
- runtime/binding-mqtt/src/main/java/io/aklivity/zilla/runtime/binding/mqtt/internal/MqttEventFormatterFactory.java
- runtime/binding-mqtt/src/main/java/io/aklivity/zilla/runtime/binding/mqtt/internal/stream/MqttServerFactory.java
- runtime/binding-mqtt/src/main/moditect/module-info.java
- runtime/binding-mqtt/src/main/resources/META-INF/services/io.aklivity.zilla.runtime.engine.event.EventFormatterFactorySpi
- runtime/binding-mqtt/src/test/java/io/aklivity/zilla/runtime/binding/mqtt/internal/stream/server/v4/ConnectionIT.java
- runtime/binding-mqtt/src/test/java/io/aklivity/zilla/runtime/binding/mqtt/internal/stream/server/v5/ConnectionIT.java
- specs/binding-mqtt.spec/src/main/resources/META-INF/zilla/mqtt.idl
- specs/binding-mqtt.spec/src/main/scripts/io/aklivity/zilla/specs/binding/mqtt/config/server.log.event.yaml
> MQTT clients access log implementation

- incubator/command-dump/src/main/java/io/aklivity/zilla/runtime/command/dump/internal/airline/ZillaDumpCommand.java
- incubator/command-dump/src/main/java/io/aklivity/zilla/runtime/command/dump/internal/airline/spy/OneToOneRingBufferSpy.java
- incubator/command-dump/src/main/java/io/aklivity/zilla/runtime/command/dump/internal/airline/spy/RingBufferSpy.java
This change makes the `dump` command sort the packets by timestamp during generation such that packet number order and timestamp order are consistent.
Fixes #959
> Sort frames by timestamp in dump command

- manager/src/main/java/io/aklivity/zilla/manager/internal/commands/install/ZpmInstall.java
- runtime/command-start/src/main/java/io/aklivity/zilla/runtime/command/start/internal/airline/ZillaStartCommand.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineConfiguration.java
> Starting Zilla with the CLI improvement

- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineManager.java
This change fixes an intermittent NPE when trying to resolve guards.
Fixes #994
> Fix NPE when trying to resolve guards

- runtime/catalog-apicurio/src/main/java/io/aklivity/zilla/runtime/catalog/apicurio/internal/ApicurioCatalogHandler.java
- runtime/catalog-apicurio/src/test/java/io/aklivity/zilla/runtime/catalog/apicurio/internal/ApicurioIT.java
- runtime/catalog-karapace/src/main/java/io/aklivity/zilla/runtime/catalog/karapace/internal/KarapaceCatalogHandler.java
- runtime/catalog-karapace/src/test/java/io/aklivity/zilla/runtime/catalog/karapace/internal/KarapaceIT.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/catalog/CatalogHandler.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/model/TestConverterHandler.java
- runtime/model-avro/src/main/java/io/aklivity/zilla/runtime/model/avro/internal/AvroReadConverterHandler.java
- runtime/model-avro/src/main/java/io/aklivity/zilla/runtime/model/avro/internal/AvroWriteConverterHandler.java
- runtime/model-json/src/main/java/io/aklivity/zilla/runtime/model/json/internal/JsonReadConverterHandler.java
- runtime/model-json/src/main/java/io/aklivity/zilla/runtime/model/json/internal/JsonWriteConverterHandler.java
- runtime/model-protobuf/src/main/java/io/aklivity/zilla/runtime/model/protobuf/internal/ProtobufReadConverterHandler.java
- runtime/model-protobuf/src/main/java/io/aklivity/zilla/runtime/model/protobuf/internal/ProtobufWriteConverterHandler.java
> Catalog Handler interface to support AWS Glue Compression

- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/metrics/reader/HistogramRecord.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/metrics/reader/ScalarRecord.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/metrics/reader/HistogramRecordTest.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/metrics/reader/ScalarRecordTest.java
- runtime/exporter-otlp/src/main/java/io/aklivity/zilla/runtime/exporter/otlp/internal/serializer/OtlpMetricsSerializer.java
- runtime/exporter-prometheus/src/main/java/io/aklivity/zilla/runtime/exporter/prometheus/internal/PrometheusExporterHandler.java
- runtime/exporter-prometheus/src/main/java/io/aklivity/zilla/runtime/exporter/prometheus/internal/printer/PrometheusMetricDescriptor.java
- runtime/exporter-prometheus/src/main/java/io/aklivity/zilla/runtime/exporter/prometheus/internal/printer/PrometheusMetricsPrinter.java
- runtime/exporter-prometheus/src/test/java/io/aklivity/zilla/runtime/exporter/prometheus/internal/printer/PrometheusMetricsPrinterTest.java
This change exports time based metrics in milliseconds that are accurate down to the nanosecond decimal place.
Fixes #1069
> Implement millisecond conversion to metrics

- incubator/command-dump/src/main/scripts/io/aklivity/zilla/runtime/command/dump/binding/tls/streams/network/connection.established/client.rpt
- incubator/command-dump/src/main/scripts/io/aklivity/zilla/runtime/command/dump/binding/tls/streams/network/connection.established/server.rpt
- incubator/command-dump/src/test/java/io/aklivity/zilla/runtime/command/dump/internal/TlsNetworkIT.java
- incubator/command-dump/src/test/resources/io/aklivity/zilla/runtime/command/dump/internal/TlsNetworkIT_shouldEstablishConnection.txt
- pom.xml
This change fixes the `TlsNetworkIt` in the `dump` command after `k3po` introduces a tls option `cipherSuites`. We set the `cipherSuites` option to a fixed value and this way we get consistent green runs for this test case in `temurin-17`, `temurin-21`, `temurin-22`.
> Fix TlsNetworkIT by adding cipherSuites

- incubator/command-dump/src/main/resources/io/aklivity/zilla/runtime/command/dump/internal/airline/zilla.lua
- incubator/command-dump/src/test/resources/io/aklivity/zilla/runtime/command/dump/internal/MqttPublishApplicationIT_shouldSendOneMessage.txt
- incubator/command-dump/src/test/resources/io/aklivity/zilla/runtime/command/dump/internal/MqttSubscribeApplicationIT_shouldReceiveOneMessage.txt
This change fixes the bug in the dump command where the packetIds array was missing from the mqtt session begin frame.
Fixes #1028
> Fix dump mqtt session begin

- cloud/helm-chart/src/main/helm/zilla/templates/deployment.yaml
This will use the values.yaml `volumes` and `volumeMounts` fields in the `deployment.yaml` to map existing resources to a zilla deployment.
> fix: add volume mounts into the deployment yaml

- runtime/engine/pom.xml
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/Engine.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineConfiguration.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/event/EngineEventContext.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/event/EngineEventFormatter.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/event/EngineEventFormatterFactory.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineManager.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineWorker.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/watcher/EngineConfigWatchTask.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/watcher/EngineConfigWatcher.java
- runtime/engine/src/main/moditect/module-info.java
- runtime/engine/src/main/resources/META-INF/services/io.aklivity.zilla.runtime.engine.event.EventFormatterFactorySpi
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/internal/event/EngineEventIT.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/exporter/TestExporterHandler.java
- runtime/engine/src/test/resources/FileSystemHelper.btm
- specs/engine.spec/src/main/resources/META-INF/zilla/core.idl
- specs/engine.spec/src/main/scripts/io/aklivity/zilla/specs/engine/config/engine.events.yaml
Creates a new `events` file for events at engine scope, in addition to per-core engine workers. Updates event reader to include these events as well so they are all picked up automatically by telemetry exporters.
Detect when `FileSystem.newWatchService()` fails, and record engine event, then still continue startup with observed `zilla.yaml` configuration.
Fixes #1081
> Support engine events and detect config watcher failed

- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/TlsEventContext.java
- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/TlsEventFormatter.java
- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/config/TlsBindingConfig.java
- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/config/TlsKeyPairVerifier.java
- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/stream/TlsClientFactory.java
- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/stream/TlsServerFactory.java
- runtime/binding-tls/src/test/java/io/aklivity/zilla/runtime/binding/tls/internal/config/TlsKeyPairVerifierTest.java
- specs/binding-tls.spec/src/main/resources/META-INF/zilla/tls.idl
This change verifies the public-private key pair obtained from vault. Logs an event if public-private key pair is invalid or missing.
Fixes #1073
> Verify public-private tls key pair

- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/TlsEventFormatter.java
- runtime/binding-tls/src/test/java/io/aklivity/zilla/runtime/binding/tls/internal/config/TlsKeyPairVerifierTest.java
Update TLS key pair verification tests to include ECDSA as well as RSA
> Enhance TLS key pair verification tests

- cloud/helm-chart/pom.xml
- cloud/pom.xml
- pom.xml
Includes `cloud/helm-chart` in non-release builds and adds explicit `lint` goal to check the helm chart during the build.
> Lint helm chart on local builds and PR builds

- cloud/helm-chart/src/main/helm/zilla/templates/NOTES.txt
- cloud/helm-chart/src/main/helm/zilla/templates/deployment.yaml
This is a simple fix in the helm chat to allow the `podLabels` field in the value.yaml to work. 
A change in the install output to correct the notes printed on install to correctly show how to port forward all of the configured service ports. 
Add an initial delay to the readiness check so the pod doesn't fail the first check when zilla hasn't started yet.
> fix: Add custom pod labels and fix notes for connection instructions

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientConnectionPool.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientGroupFactory.java
We are using flow control budget to manage multiple requests on shared connection from pool, so multiple small requests can successfully claim non-fragmented budget and send both requests.
They could arrive in any order in practice. When sent via TLS, there is potential for batching at encryption layer so a single window can be received to ack both requests in the aggregate.
When we distribute the flow control credit to each stream, we need to make sure not to over credit beyond the amount actually sent by each stream. Otherwise, we would not hit the condition to precisely ack the data sent by the first stream, and therefore it is not removed from the queue, blocking ack for all subsequent streams.
When this occurs, subsequent streams on the shared connection in the pool will eventually …
> Support multiple requests with single window ack on shared connection

- runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/config/AsyncapiHttpKafkaProxy.java
- runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/config/AsyncapiIdentity.java
- runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/config/AsyncapiMqttKafkaProxy.java
- runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/config/AsyncapiProxy.java
- runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/config/AsyncapiProxyNamespaceGenerator.java
- runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/config/AsyncapiSseKafkaProxy.java
- runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/model/AsyncapiBinding.java
- runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/model/AsyncapiKafkaFilter.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/config/HttpKafkaWithFetchConfigBuilder.java
- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/config/HttpKafkaWithProduceConfigBuilder.java
- specs/binding-asyncapi.spec/src/main/scripts/io/aklivity/zilla/specs/binding/asyncapi/config/proxy.http.kafka.yaml
- specs/binding-asyncapi.spec/src/main/scripts/io/aklivity/zilla/specs/binding/asyncapi/streams/asyncapi/proxy.http.create.pet/server.rpt
> Support `http-kafka` header overrides from AsyncAPI http operation

- cloud/helm-chart/src/main/helm/zilla/templates/NOTES.txt
- cloud/helm-chart/src/main/helm/zilla/templates/ingress.yaml
- cloud/helm-chart/src/main/helm/zilla/values.yaml
This improves the ingress controller to allow for managing ingress without a host specified. It also enables defining paths that can map to different ports down to the K8s zilla service. Additionally, it supports backward-compatible K8s versions of ingress.
Notes output with multiple ingress paths defined:
```
Zilla is available through an ingress controller at the base url(s):
http://localhost/api
http://localhost/ui
```
Notes output when no ingress is configured, the command dynamically forwards any exposed Zilla service ports:
```
Connect to Zilla by running these commands:
export SERVICE_PORTS=$(kubectl get svc --namespace $namespace $service_name --template "{{ range .spec.ports }}{{.port}} {{ end }}")
eval "kubectl port-forward --namespace $namespace service/$service_name …
```
> update ingress values and implementation

- runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/config/composite/AsyncapiCompositeGenerator.java
- runtime/catalog-apicurio/src/main/java/io/aklivity/zilla/runtime/catalog/apicurio/config/ApicurioOptionsConfig.java
- runtime/catalog-apicurio/src/main/java/io/aklivity/zilla/runtime/catalog/apicurio/config/ApicurioOptionsConfigBuilder.java
- runtime/catalog-apicurio/src/main/java/io/aklivity/zilla/runtime/catalog/apicurio/internal/ApicurioCatalogContext.java
- runtime/catalog-apicurio/src/main/java/io/aklivity/zilla/runtime/catalog/apicurio/internal/ApicurioCatalogHandler.java
- runtime/catalog-apicurio/src/main/java/io/aklivity/zilla/runtime/catalog/apicurio/internal/config/ApicurioOptionsConfigAdapter.java
- runtime/catalog-apicurio/src/main/moditect/module-info.java
- runtime/catalog-apicurio/src/test/java/io/aklivity/zilla/runtime/catalog/apicurio/internal/ApicurioCatalogIT.java
- runtime/catalog-apicurio/src/test/java/io/aklivity/zilla/runtime/catalog/apicurio/internal/config/ApicurioOptionsConfigAdapterTest.java
> Enables `bindings:asyncapi` to use `catalog::apicurio`

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/cache/KafkaCacheCursorFactory.java
Needed by mqtt-kafka for root multilevel wildcard `#` which is an automatic subscription used by [MQTT Explorer](https://mqtt-explorer.com/).
> Support SKIP_MANY only kafka headers sequence filter

- runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/stream/HttpServerFactory.java
- runtime/binding-http/src/test/java/io/aklivity/zilla/runtime/binding/http/internal/streams/rfc7540/server/StartingIT.java
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/network/rfc7540/starting/upgrade.h2c.with.no.settings/client.rpt
- specs/binding-http.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/streams/network/rfc7540/starting/upgrade.h2c.with.no.settings/server.rpt
When `upgrade` is observed in the http 1.1 headers after `content-length`, it was enforcing that no body decoder is in place, just headers only before the upgrade. However, `content-length` is valid specifically for `h2c` upgrade.
Fixes #1192
> Allow content-length header with h2c upgrade

- runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/config/composite/AsyncapiClientGenerator.java
Using `asyncapi client` binding trigger NPE & crashes Zilla 
**To Reproduce**
Steps to reproduce the behavior:
1. Pull latest zilla changes & create a local build.  
2. Update [asyncapi example](https://github.com/aklivity/zilla-examples/tree/main/asyncapi.http.kafka.proxy ) to use develop-SNAPSHOT version of zilla
3. On start, zilla crashes with mentioned error:
```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "topics" is null
at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
...
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "topics" is null
at io.aklivity.zilla.runtime.binding.asyncapi@0.9.92/io.aklivity.zilla.runtime.binding.a …
```
> Fix: Using `asyncapi client` binding trigger NPE & crashes Zilla

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaClientProduceFactory.java
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/produce/message.header/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/produce/message.value.100k/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/network/produce.v3/message.header/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/network/produce.v3/message.header/server.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/network/produce.v3/message.value.100k/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/network/produce.v3/message.value.100k/server.rpt
Kafka produce protocol requires crc32c checksum up front before the message value and headers. When messages are small, we have all the information at once, i.e. the complete value and the headers, so we can easily compute the checksum. When the message is fragmented, we have the headers with `init` fragment, and checksum of complete value, so we can compute the full checksum without staging the headers themselves temporarily. Then the headers are sent again with the `fin` fragment so we can include them after the message value, per the Kafka produce protocol format.
Fixes #1046
> Compute kafka produce checksum without staging headers

- runtime/catalog-apicurio/src/main/java/io/aklivity/zilla/runtime/catalog/apicurio/internal/ApicurioCatalogHandler.java
- runtime/catalog-apicurio/src/main/zilla/internal.idl
- runtime/catalog-apicurio/src/test/java/io/aklivity/zilla/runtime/catalog/apicurio/internal/ApicurioCatalogHandlerTest.java
- runtime/catalog-apicurio/src/test/java/io/aklivity/zilla/runtime/catalog/apicurio/internal/ApicurioCatalogIT.java
> Ensure id encoding is consistent for encode and decode

- build/flyweight-maven-plugin/src/main/java/io/aklivity/zilla/build/maven/plugins/flyweight/internal/AbstractMojo.java
- conf/src/main/resources/io/aklivity/zilla/conf/checkstyle/configuration.xml
- conf/src/main/resources/io/aklivity/zilla/conf/checkstyle/suppressions.xml
Ignore checkstyle errors for generated sources and handle non-JAR project dependencies to resolve idl files when Eclipse M2E resolves Maven dependencies as peer Eclipse project instead.
> Eclipse IDE import maven projects

- .github/workflows/links-check.yml
- README.md
add a GH Action to check links on the README
> Link checker

- cloud/docker-image/pom.xml
`zilla` build fails with mentioned error:
```
[INFO] DOCKER> #13 3.399 :: problems summary ::
[INFO] DOCKER> #13 3.399 :::: WARNINGS
[INFO] DOCKER> #13 3.399 		module not found: io.aklivity.zilla#binding-pgsql-kafka;develop-SNAPSHOT
```
> `zilla` build fix

- runtime/catalog-schema-registry/src/main/java/io/aklivity/zilla/runtime/catalog/schema/registry/internal/handler/SchemaRegistryCatalogHandler.java
- runtime/catalog-schema-registry/src/test/java/io/aklivity/zilla/runtime/catalog/schema/registry/internal/SchemaRegistryIT.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/catalog/CatalogHandler.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/binding/TestBindingFactory.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/binding/config/TestBindingOptionsConfig.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/binding/config/TestBindingOptionsConfigAdapter.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/binding/config/TestBindingOptionsConfigBuilder.java
- specs/catalog-schema-registry.spec/src/main/scripts/io/aklivity/zilla/specs/catalog/schema/registry/config/register/zilla.yaml
- specs/catalog-schema-registry.spec/src/main/scripts/io/aklivity/zilla/specs/catalog/schema/registry/streams/register.schema.rpt
- specs/engine.spec/src/main/scripts/io/aklivity/zilla/specs/engine/schema/binding/test.schema.patch.json
- specs/engine.spec/src/main/scripts/io/aklivity/zilla/specs/engine/schema/engine.schema.json
Support catalog register new schema version.
Fixes #1060
> Support catalog register new schema version

- specs/guard-jwt.spec/src/main/scripts/io/aklivity/zilla/specs/guard/jwt/schema/jwt.schema.patch.json
updates the type for the challenge options on the jwt guard.
> fix: use integer for challenge type

- incubator/binding-pgsql-kafka/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/kafka/internal/stream/PgsqlKafkaCommandType.java
- incubator/binding-pgsql-kafka/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/kafka/internal/stream/PgsqlKafkaCompletionCommand.java
- incubator/binding-pgsql-kafka/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/kafka/internal/stream/PgsqlKafkaProxyFactory.java
- incubator/binding-pgsql-kafka/src/test/java/io/aklivity/zilla/runtime/binding/pgsql/kafka/internal/stream/ProxyIT.java
- runtime/catalog-schema-registry/src/main/java/io/aklivity/zilla/runtime/catalog/schema/registry/internal/handler/SchemaRegistryCatalogHandler.java
- runtime/catalog-schema-registry/src/main/java/io/aklivity/zilla/runtime/catalog/schema/registry/internal/serializer/UnregisterSchemaRequest.java
- runtime/catalog-schema-registry/src/test/java/io/aklivity/zilla/runtime/catalog/schema/registry/internal/SchemaRegistryIT.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/catalog/CatalogHandler.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/binding/TestBindingFactory.java
- specs/catalog-schema-registry.spec/src/main/scripts/io/aklivity/zilla/specs/catalog/schema/registry/config/unregister/zilla.yaml
- specs/catalog-schema-registry.spec/src/main/scripts/io/aklivity/zilla/specs/catalog/schema/registry/streams/unregister.schema.rpt
`pgsql` DELETE TOPIC command to KafkaDeleteTopicsBeginEx plus catalog unregister subject
See #1058
> `pgsql` DROP TOPIC command to KafkaDeleteTopicsBeginEx plus catalog unregister subject

- incubator/binding-pgsql.spec/src/main/java/io/aklivity/zilla/specs/binding/pgsql/PgsqlFunctions.java
- incubator/binding-pgsql.spec/src/main/resources/META-INF/zilla/pgsql.idl
- incubator/binding-pgsql.spec/src/main/scripts/io/aklivity/zilla/specs/binding/pgsql/streams/application/select.table.with.error/client.rpt
- incubator/binding-pgsql.spec/src/main/scripts/io/aklivity/zilla/specs/binding/pgsql/streams/application/select.table.with.error/server.rpt
- incubator/binding-pgsql.spec/src/main/scripts/io/aklivity/zilla/specs/binding/pgsql/streams/network/select.table.with.error/client.rpt
- incubator/binding-pgsql.spec/src/main/scripts/io/aklivity/zilla/specs/binding/pgsql/streams/network/select.table.with.error/server.rpt
- incubator/binding-pgsql.spec/src/main/scripts/io/aklivity/zilla/specs/binding/pgsql/streams/network/select.table/server.rpt
- incubator/binding-pgsql.spec/src/test/java/io/aklivity/zilla/specs/binding/pgsql/streams/ApplicationIT.java
- incubator/binding-pgsql.spec/src/test/java/io/aklivity/zilla/specs/binding/pgsql/streams/NetworkIT.java
- incubator/binding-pgsql.spec/src/test/java/io/aklivity/zilla/specs/binding/pgsql/streams/internal/PgsqlFunctionsTest.java
- incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/internal/stream/PgsqlClientFactory.java
- incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/internal/stream/PgsqlServerFactory.java
- incubator/binding-pgsql/src/test/java/io/aklivity/zilla/runtime/binding/pgsql/internal/stream/ClientIT.java
- incubator/binding-pgsql/src/test/java/io/aklivity/zilla/runtime/binding/pgsql/internal/stream/ServerIT.java
- incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/streams/effective/query.with.multiple.statements.errored/client.rpt
- incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/streams/effective/query.with.multiple.statements.errored/server.rpt
- incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/streams/pgsql/query.with.multiple.statements.errored/client.rpt
- incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/streams/pgsql/query.with.multiple.statements.errored/server.rpt
- incubator/binding-risingwave.spec/src/test/java/io/aklivity/zilla/specs/binding/risingwave/streams/EffectiveIT.java
- incubator/binding-risingwave.spec/src/test/java/io/aklivity/zilla/specs/binding/risingwave/streams/PgsqlIT.java
- incubator/binding-risingwave/src/main/java/io/aklivity/zilla/runtime/binding/risingwave/internal/stream/RisingwaveProxyFactory.java
- incubator/binding-risingwave/src/test/java/io/aklivity/zilla/runtime/binding/risingwave/internal/stream/ProxyIT.java
Propagate error code in risingwave binding that's coming either from pgsql-kafka or risingwave
Fixes #1286
> Propagate error code in risingwave binding that's coming either from pgsql-kafka or risingwave

- runtime/filesystem-http/src/main/java/io/aklivity/zilla/runtime/filesystem/http/internal/HttpPath.java
Before this change, if the initial request for `zilla.yaml` receives `404` not found, then the next watch request would not include `prefer: wait=N` so it can return immediately with `404` also, causing the next watch request to be sent only after a poll interval, which is `60s` by default.
After this change, even if the initial request for `zilla.yaml` receives `404`, then the next watch request now includes `prefer: wait=N` and responds immediately when the response becomes available, with no need for polling.
> Include prefer wait in watch request even after initial 404 read request

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/KafkaConfiguration.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaCacheServerFetchFactory.java
- runtime/binding-kafka/src/test/java/io/aklivity/zilla/runtime/binding/kafka/internal/KafkaConfigurationTest.java
- runtime/binding-kafka/src/test/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/CacheFetchIT.java
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/config/cache.options.live.yaml
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/fetch/messages.after.retention.max/client.rpt
- specs/binding-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/kafka/streams/application/fetch/messages.after.retention.max/server.rpt
Fixes https://github.com/aklivity/zilla/issues/1291
> Fix kafka cache fetch server retention issue

- cloud/docker-image/src/main/docker/Dockerfile
- runtime/command/src/main/moditect/module-info.java
When attempting to use Java instrumentation agents, `zilla` gives the following error.
```
java.lang.module.FindException: Module java.instrument not found error.
```
This change includes `java.instrument` module in the `zilla` java linked runtime, and opens the main class package to allow the instrumentation to succeed on startup.
> Support instrumentation via Java agent

- manager/src/main/java/io/aklivity/zilla/manager/internal/commands/install/ZpmInstall.java
`jdeps` generates a `module-info.java` that exports packages even if they have only `package-info.class`.
`jlink` complains that a package is empty, even if it includes `package-info.class`.
So, we need to exclude `package-info.class` from the delegate module to prevent `jdeps` from generating a `module-info.java` that is incompatible with `jlink`.
> Exclude package-info.class from delegate module to avoid empty packages

- runtime/binding-grpc/src/main/antlr4/io/aklivity/zilla/runtime/binding/grpc/internal/parser/Protobuf3.g4
- runtime/binding-grpc/src/main/java/io/aklivity/zilla/runtime/binding/grpc/internal/config/GrpcServiceDefinitionListener.java
- specs/binding-grpc.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/config/protobuf/echo.proto
Fixes https://github.com/aklivity/zilla/issues/1230
> Improve gRPC parser to allow complex types in optionValue

- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/config/KafkaTopicHeaderConfig.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/config/KafkaTopicHeaderType.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/config/KafkaTopicTransformsConfig.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/config/KafkaTopicTransformsConfigBuilder.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/cache/KafkaCachePartition.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/config/KafkaTopicHeaderType.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/config/KafkaTopicTransformsConfigAdapter.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/config/KafkaTopicTransformsType.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/config/KafkaTopicType.java
- runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/stream/KafkaCacheServerFetchFactory.java
- runtime/binding-kafka/src/test/java/io/aklivity/zilla/runtime/binding/kafka/internal/config/KafkaOptionsConfigAdapterTest.java
> fix: kafka header extraction expression in composite zilla.yaml

- runtime/catalog-apicurio/src/main/java/io/aklivity/zilla/runtime/catalog/apicurio/internal/ApicurioCatalogHandler.java
- runtime/catalog-schema-registry/src/main/java/io/aklivity/zilla/runtime/catalog/schema/registry/internal/handler/SchemaRegistryCatalogHandler.java
When we have a schema ID (int), that's more than 3 digit, catalog handler unable to pull schema.
Cause: 
MessageFormat.format() treats numbers according to locale-specific formatting rules. By default, it inserts a thousands separator (comma in some locales) when formatting numbers larger than 999.
Fixes #1391
> fix: locale-specific formatting due to `MessageFormat.format()`

- runtime/binding-grpc-kafka/pom.xml
- runtime/binding-grpc-kafka/src/main/java/io/aklivity/zilla/runtime/binding/grpc/kafka/internal/config/GrpcKafkaWithProduceConfigAdapter.java
- runtime/binding-grpc-kafka/src/main/java/io/aklivity/zilla/runtime/binding/grpc/kafka/internal/config/GrpcKafkaWithProduceResult.java
- runtime/binding-grpc-kafka/src/main/java/io/aklivity/zilla/runtime/binding/grpc/kafka/internal/stream/GrpcKafkaProxyFactory.java
- runtime/binding-grpc-kafka/src/test/java/io/aklivity/zilla/runtime/blinding/grpc/kafka/internal/stream/GrpcKafkaProduceProxyIT.java
- specs/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/config/produce.proxy.rpc.oneway.yaml
- specs/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/schema/grpc.kafka.schema.patch.json
- specs/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/streams/grpc/produce/client.stream.rpc.oneway/client.rpt
- specs/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/streams/grpc/produce/client.stream.rpc.oneway/server.rpt
- specs/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/streams/grpc/produce/unary.rpc.oneway/client.rpt
- specs/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/streams/grpc/produce/unary.rpc.oneway/server.rpt
- specs/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/streams/kafka/produce/client.stream.rpc.oneway/client.rpt
- specs/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/streams/kafka/produce/client.stream.rpc.oneway/server.rpt
- specs/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/streams/kafka/produce/unary.rpc.oneway/client.rpt
- specs/binding-grpc-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/kafka/streams/kafka/produce/unary.rpc.oneway/server.rpt
- specs/binding-grpc-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/grpc/kafka/streams/GrpcProduceIT.java
- specs/binding-grpc-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/grpc/kafka/streams/KafkaProduceIT.java
- specs/binding-grpc.spec/src/main/scripts/io/aklivity/zilla/specs/binding/grpc/config/protobuf/oneway.proto
> Support gRPC client stream/unary oneway

- runtime/binding-echo/src/test/java/io/aklivity/zilla/runtime/binding/echo/internal/bench/EchoWorker.java
- runtime/binding-tls/src/test/java/io/aklivity/zilla/runtime/binding/tls/internal/bench/TlsWorker.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineContext.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineRegistry.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineWorker.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/NamespaceRegistry.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/binding/TestBindingFactory.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/binding/config/TestBindingOptionsConfig.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/binding/config/TestBindingOptionsConfigAdapter.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/binding/config/TestBindingOptionsConfigBuilder.java
- runtime/exporter-otlp/src/test/java/io/aklivity/zilla/runtime/exporter/otlp/internal/MetricsIT.java
- specs/engine.spec/src/main/scripts/io/aklivity/zilla/specs/engine/schema/binding/test.schema.patch.json
- specs/exporter-otlp.spec/src/main/scripts/io/aklivity/zilla/specs/exporter/otlp/config/metrics.with.service.name.yaml
- specs/exporter-otlp.spec/src/main/scripts/io/aklivity/zilla/specs/exporter/otlp/config/metrics.yaml
> fix: resolveKind flow for composite binding

- runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/config/composite/AsyncapiCompositeGenerator.java
- runtime/binding-openapi/src/main/java/io/aklivity/zilla/runtime/binding/openapi/internal/config/composite/OpenapiCompositeGenerator.java
- runtime/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/config/BooleanModelConfig.java
- runtime/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/config/BooleanModelConfigBuilder.java
- runtime/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/internal/BooleanConverterHandler.java
- runtime/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/internal/BooleanModel.java
- runtime/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/internal/BooleanModelContext.java
- runtime/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/internal/BooleanModelFactorySpi.java
- runtime/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/internal/BooleanValidatorHandler.java
- runtime/model-core/src/main/java/io/aklivity/zilla/runtime/model/core/internal/config/BooleanModelConfigAdapter.java
- runtime/model-core/src/main/moditect/module-info.java
- runtime/model-core/src/main/resources/META-INF/services/io.aklivity.zilla.runtime.engine.config.ModelConfigAdapterSpi
- runtime/model-core/src/main/resources/META-INF/services/io.aklivity.zilla.runtime.engine.model.ModelFactorySpi
- runtime/model-core/src/test/java/io/aklivity/zilla/runtime/model/core/internal/BooleanModelFactoryTest.java
- runtime/model-core/src/test/java/io/aklivity/zilla/runtime/model/core/internal/BooleanValidatorTest.java
- runtime/model-core/src/test/java/io/aklivity/zilla/runtime/model/core/internal/config/BooleanModelConfigAdapterTest.java
- specs/model-core.spec/src/main/scripts/io/aklivity/zilla/specs/model/core/config/boolean.model.yaml
- specs/model-core.spec/src/main/scripts/io/aklivity/zilla/specs/model/core/schema/boolean.schema.patch.json
- specs/model-core.spec/src/test/java/io/aklivity/zilla/specs/model/core/config/BooleanSchemaTest.java
> support boolean model

- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/stream/TlsClientFactory.java
- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/stream/TlsServerFactory.java
Current assumption is that `tlsEngine.closeOutbound()` should immediately end the stream, so `END` frame follows.
Instead we need to verify `tlsEngine.isOutboundDone()` before sending `END` frame.
> Handle TLS Alert.USER_CANCELED then deferred Alert.CLOSE_NOTIFY

- runtime/exporter-prometheus/src/main/java/io/aklivity/zilla/runtime/exporter/prometheus/internal/printer/PrometheusMetricsPrinter.java
- runtime/exporter-prometheus/src/test/java/io/aklivity/zilla/runtime/exporter/prometheus/internal/printer/PrometheusMetricsPrinterTest.java
The test [PrometheusMetricsPrinterTest.shouldWorkWithMilliseconds()](https://github.com/aklivity/zilla/blob/b3f686c8d6646a3affeba4c2668da0a7801dd3cd/runtime/exporter-prometheus/src/test/java/io/aklivity/zilla/runtime/exporter/prometheus/internal/printer/PrometheusMetricsPrinterTest.java#L104) fails when the default JVM locale does not use  dot (`.`) as the decimal separator, because floating point numbers are formatted differently and the string comparison does not match.
**Solution**: explicitly set the locale to `Locale.US` when formatting decimal numbers. This makes the test pass regardless of the JVM locale settings and generally ensures more consistent behaviour because the output is independent from the JVM local configuration.
> Fix failing test when JVM default locale is not US

- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineConfiguration.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/internal/EngineTest.java
> Fix default worker capacity

- incubator/binding-amqp/src/main/java/io/aklivity/zilla/runtime/binding/amqp/internal/stream/AmqpServerFactory.java
- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/stream/TlsClientFactory.java
- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/stream/TlsProxyFactory.java
- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/stream/TlsServerFactory.java
Avoids issues with `int` when `long` data typed `ack` becomes greater than `Integer.MAX_VALUE`.
> Use long not int when calculating ack max

- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/stream/TlsClientFactory.java
- runtime/binding-tls/src/main/java/io/aklivity/zilla/runtime/binding/tls/internal/stream/TlsServerFactory.java
Handle case where TLS client handshake task is pending but has been canceled by closing the network initial stream.
Apply same simplification to TLS server.
> Simplify TLS decode loop by inlining decodeHandshakeNeedTask

- .github/workflows/build.yml
- examples/asyncapi.sse.proxy/.github/test.sh
- examples/asyncapi.sse.proxy/compose.yaml
- examples/asyncapi.sse.proxy/etc/specs/sse-asyncapi.yaml
- runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/internal/config/composite/AsyncapiServerGenerator.java
- specs/binding-asyncapi.spec/src/main/scripts/io/aklivity/zilla/specs/binding/asyncapi/streams/asyncapi/sse/data.multiple/client.rpt
- specs/binding-asyncapi.spec/src/main/scripts/io/aklivity/zilla/specs/binding/asyncapi/streams/asyncapi/sse/data.multiple/server.rpt
- specs/binding-asyncapi.spec/src/main/scripts/io/aklivity/zilla/specs/binding/asyncapi/streams/composite/sse/data.multiple/client.rpt
- specs/binding-asyncapi.spec/src/main/scripts/io/aklivity/zilla/specs/binding/asyncapi/streams/composite/sse/data.multiple/server.rpt
> added support for validation in asyncapi.sse flow & example fix

- .github/workflows/build.yml
- examples/asyncapi.sse.kafka.proxy/.github/test.sh
- examples/asyncapi.sse.kafka.proxy/compose.yaml
- examples/asyncapi.sse.kafka.proxy/etc/specs/kafka-asyncapi.yaml
- examples/asyncapi.sse.kafka.proxy/etc/specs/sse-asyncapi.yaml
> fix `asyncapi.sse.kafka.proxy` example & enable `test`

- runtime/binding-http-kafka/src/main/java/io/aklivity/zilla/runtime/binding/http/kafka/internal/config/HttpKafkaWithProduceHash.java
- runtime/binding-http-kafka/src/test/java/io/aklivity/zilla/runtime/binding/http/kafka/internal/stream/HttpKafkaProxyIT.java
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/post.item.command.10k/client.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/http/post.item.command.10k/server.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/kafka/post.item.command.10k/client.rpt
- specs/binding-http-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/http/kafka/streams/kafka/post.item.command.10k/server.rpt
- specs/binding-http-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/http/kafka/streams/HttpIT.java
- specs/binding-http-kafka.spec/src/test/java/io/aklivity/zilla/specs/binding/http/kafka/streams/KafkaIT.java
- specs/binding-http.spec/src/main/java/io/aklivity/zilla/specs/binding/http/internal/HttpFunctions.java
- specs/binding-http.spec/src/test/java/io/aklivity/zilla/specs/binding/http/internal/HttpFunctionsTest.java
Fixes https://github.com/aklivity/zilla/issues/1479
> Fix large message hashing in http-kafka

- runtime/binding-tcp/src/main/java/io/aklivity/zilla/runtime/binding/tcp/internal/TcpCapacityTracker.java
- runtime/binding-tcp/src/main/java/io/aklivity/zilla/runtime/binding/tcp/internal/stream/TcpClientFactory.java
- runtime/binding-tcp/src/main/java/io/aklivity/zilla/runtime/binding/tcp/internal/stream/TcpClientRouter.java
- runtime/binding-tcp/src/main/java/io/aklivity/zilla/runtime/binding/tcp/internal/stream/TcpServerRouter.java
- runtime/binding-tcp/src/test/java/io/aklivity/zilla/runtime/binding/tcp/internal/SocketChannelHelper.java
- runtime/binding-tcp/src/test/java/io/aklivity/zilla/runtime/binding/tcp/internal/streams/ClientIT.java
- runtime/binding-tcp/src/test/java/io/aklivity/zilla/runtime/binding/tcp/internal/streams/ClientPartialWriteIT.java
- runtime/binding-tcp/src/test/java/io/aklivity/zilla/runtime/binding/tcp/internal/streams/ServerIT.java
- runtime/binding-tcp/src/test/resources/SocketChannelHelper.btm
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/Engine.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/ext/EngineExtContext.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/layouts/metrics/CountersLayout.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/layouts/metrics/GaugesLayout.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/layouts/metrics/ScalarsLayout.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/metrics/EngineMetricGroup.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/metrics/EngineWorkerCountMetric.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/metrics/EngineWorkerUtilizationMetric.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineWorker.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/internal/EngineConfigurationTest.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/internal/layouts/metrics/CountersLayoutTest.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/internal/layouts/metrics/GaugesLayoutTest.java
- runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/EngineRule.java
- specs/binding-tcp.spec/src/main/scripts/io/aklivity/zilla/specs/binding/tcp/streams/application/rfc793/client.close.immediately/client.rpt
- specs/binding-tcp.spec/src/main/scripts/io/aklivity/zilla/specs/binding/tcp/streams/application/rfc793/client.close.immediately/server.rpt
- specs/binding-tcp.spec/src/test/java/io/aklivity/zilla/specs/binding/tcp/streams/ApplicationIT.java
Engine metric for worker utilization is an absolute value, so should be recorded via Gauge semantics rather than specifying delta to accumulating Counter semantics.
> Use GaugesLayout for engine worker capacity metric

- examples/tcp.echo/compose.yaml
- runtime/binding-tcp/src/main/java/io/aklivity/zilla/runtime/binding/tcp/internal/TcpCapacityTracker.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/EngineConfiguration.java
- runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/registry/EngineWorker.java
`-w 1`
```
root@zilla:/# ls -l /var/run/zilla/
total 1050284
-rw-r--r-- 1 root root        80 Jun 15 01:12 bindings
-rw-r--r-- 1 root root   1048576 Jun 15 01:12 budgets0
-rw-r--r-- 1 root root 537001988 Jun 15 01:12 buffers0
-rw-r--r-- 1 root root 536871680 Jun 15 01:12 data0
-rw-r--r-- 1 root root    262912 Jun 15 01:12 events
-rw-r--r-- 1 root root    262912 Jun 15 01:12 events0
-rw-r--r-- 1 root root        12 Jun 15 01:12 info
-rw-r--r-- 1 root root       749 Jun 15 01:12 labels
drwxr-xr-x 2 root root      4096 Jun 15 01:12 metrics
-rw-r--r-- 1 root root        32 Jun 15 01:12 tuning
root@zilla:/opt/zilla# ./zilla metrics
namespace    binding    metric                        value
engine.workers.utilization        0
engine.workers.count              1
engine.workers.capacity …
```
> Support `engine.worker.capacity.unbounded` configuration

- runtime/binding-tcp/src/main/java/io/aklivity/zilla/runtime/binding/tcp/internal/stream/TcpClientFactory.java
- In Selector, `OP_CONNECT` means “the socket is ready to finish the connection”, not necessarily that the handshake is complete.
- This readiness is based on low-level OS signals:
- On Linux/BSD/macOS: the kernel sets socket writable once the handshake progresses enough for `connect()` to be completed or fails immediately.
- The selector interprets a writable socket in non-blocking connect as `OP_CONNECT` ready.
- Key point: ready-to-finish does not guarantee `finishConnect()` will succeed immediately.
Even after the OS signals writable / `OP_CONNECT` ready:
- The TCP handshake may still be in progress (delays, packet loss, retransmission).
- The channel must call `finishConnect()` to:
- Complete the handshake in Java’s `SocketChannel` API.
- Update the internal channel state.
- Assign …
> Handle slow TCP client handshake
